oneapi-src/distributed-ranges

- doc/spec/source/algorithms/copy.rst
- include/dr/algorithms/algorithms.hpp
- include/dr/details/communicator.hpp
- test/fuzz/cpu/cpu-fuzz.cpp
- test/gtest/cpu/algorithms.cpp
I tried to clean up all the stuff related to copy
- functions are in SPMD style (one function accepting either iterators or nullptr)
- functions have consistent signatures ('concept auto name' whenever possible instead of template, unless we need the same type for two params)
- functions have short consistent comments
Maybe it is not best to review the change itself (or not only to review the change), but to look how all copy functions currently look and if we like how do they look.
PR is based on https://github.com/oneapi-src/distributed-ranges/pull/4
> copy operations final cleanups

- include/dr/mhp/algorithms/cpu_algorithms.hpp
- include/dr/mhp/containers/distributed_vector.hpp
- test/gtest/mhp/conformance.cpp
- iterators are used to be taked by value in STL (let's don't use references to iterator, references to iterators do not satisfy std::forward_iterator concept)
- conformat uses now distributed_iterator types only
- simply returns bool
> conformant function simplified

- include/dr/concepts/concepts.hpp
- include/dr/details/ranges.hpp
- include/dr/details/segments_tools.hpp
- include/dr/details/view_detectors.hpp
- include/dr/mhp.hpp
- include/dr/mhp/algorithms/cpu_algorithms.hpp
- include/dr/mhp/containers/distributed_vector.hpp
- include/dr/mhp/cpos.hpp
- include/dr/mhp/views.hpp
- test/gtest/include/common-tests.hpp
- test/gtest/mhp/mhp-tests.cpp
- test/gtest/mhp/views.cpp
Allow parallel algorithms on `zip_view` that contain `distributed_range`. Uses CPO's to provide `segments` and friends. Adding support for `transform_view` should leverage the same code.
I will handle zips that contain iota and misaligned distributed vectors in a separate PR.
@lslusarczyk and @BenBrock: Feedback is welcome.
> mhp support for rng::zip_view

- test/gtest/shp/views.cpp
Tests for shp zip
Works fine for zip with >= 3. Does not work for 2 so I ifdef'd that case. The problem is not a bug, but is an inconvenience.
@BenBrock
> test for shp zip

- CMakeLists.txt
- examples/shp/test_range.cpp
- include/dr/shp/device_span.hpp
- include/dr/shp/device_vector.hpp
- include/dr/shp/distributed_vector.hpp
- include/dr/shp/vector.hpp
- include/dr/shp/zip_view.hpp
- test/gtest/shp/views.cpp
Turned on warnings for shp-specific code and fixed issues. You can disable specific warnings this way: https://github.com/oneapi-src/distributed-ranges/blob/8c9852e73518107aaa88d959eef0d2be09fdf53e/CMakeLists.txt#L143
None of the issues were bugs, but they are still worth fixing.
* unused variables
* reference to uninitialized variable
* initializer list order does not match constructor order
```
/nfs/site/home/rscohn1/local/projects/dds/dr/include/./dr/shp/device_span.hpp:56:14: error: field 'rank_' will be initialized afte      base 'shp::span<int, device_ptr<int>>' [-Werror,-Wreorder-ctor]
:        rank_(lib::ranges::rank(r)),
^~~~~~~~~~~~~~~~~~~~~~~~~~~
shp::span<T, Iter>(rng::begin(r), rng::size(r))
```
> turn on Wall/Werror for shp and fix issues

- .github/workflows/ci.yml
- CMakeLists.txt
- test/gtest/shp/CMakeLists.txt
inclusive scan has intermittent failures. Change CI so it will run the test and report results, but not fail the CI.
@BenBrock: I thought it was just shp3 (3 devices), but shp also fails in inclusive scan.
> prevent inclusive scan from failing CI

- CMakeLists.txt
- include/dr/mhp.hpp
- include/dr/mhp/algorithms/algorithms.hpp
- include/dr/mhp/sycl_support.hpp
- test/gtest/mhp-sycl/CMakeLists.txt
- test/gtest/mhp-sycl/algorithms.cpp
- test/gtest/mhp/algorithms.cpp
Implement for_each in mhp-sycl
don't emit deprecated warnings. DPL generates so many, it is hard to see real issues.
> mhp-sycl for_each

- .pre-commit-config.yaml
- examples/shp/dot_product.cpp
- examples/shp/gemv_example.cpp
- examples/shp/inclusive_scan_example.cpp
- examples/shp/matrix_example.cpp
- examples/shp/sparse_test.cpp
- examples/shp/take_example.cpp
- examples/shp/test_range.cpp
- examples/shp/vector_example.cpp
- examples/shp/zip_example.cpp
- include/dr/shp/algorithms/execution_policy.hpp
- include/dr/shp/algorithms/for_each.hpp
- include/dr/shp/algorithms/gemv.hpp
- include/dr/shp/algorithms/inclusive_scan.hpp
- include/dr/shp/algorithms/reduce.hpp
- include/dr/shp/allocators.hpp
- include/dr/shp/copy.hpp
- include/dr/shp/device_ptr.hpp
- include/dr/shp/device_ref.hpp
- include/dr/shp/distributed_vector.hpp
- include/dr/shp/init.hpp
- include/dr/shp/util.hpp
- scripts/dr-style.py
- test/gtest/shp/shp-tests.hpp
Reusing a script I wrote for another project. It does simple pattern match to find style issues.
I updated our includes/namespace to sycl2020. Added to pre-commit
Some of the rules were my personal preference for concise sycl code and could be relaxed.
> add dr-style and correct errors

- CMakeLists.txt
I'm hitting this issue when compiling `fmt` with the latest dpcpp: https://github.com/fmtlib/fmt/issues/3005
Updating `fmt` git tag to include the corresponding fix https://github.com/fmtlib/fmt/commit/0b0f7cfbfcebd021c910078003d413354bd843e2
> Update fmt git tag

- README.rst
- test/fuzz/README.rst
- test/fuzz/cpu/algorithms.cpp
- test/fuzz/cpu/cpu-fuzz.cpp
- test/fuzz/cpu/cpu-fuzz.hpp
The fuzzer was getting random failures. It turns out that it was completely broken, but the way I set up the search space, it was rarely executing any test cases for short runs. I changed the search space so most patterns execute a real test. Fixed issues.
Fixes #71
> fix fuzzer issues

- include/dr/details/communicator.hpp
- include/dr/mhp/algorithms/algorithms.hpp
- include/dr/mhp/views.hpp
MPI uses `int` for rank. DR uses `size_t`. Do the conversion in `communicator.hpp` to make DR code more uniform.
> change communicator size/rank to size_t

- CMakeLists.txt
Debug info is 100Mbytes for mhp-tests. This speeds up build, but it is still slow.
> turn off -g for Release build

- .pre-commit-config.yaml
- include/dr/details/remote_subrange.hpp
- include/dr/mhp/algorithms/algorithms.hpp
- include/dr/mhp/algorithms/reduce.hpp
- include/dr/mhp/alignment.hpp
- include/dr/mhp/containers/distributed_vector.hpp
- include/dr/mhp/views.hpp
- scripts/dr-style.py
@BenBrock: I extended the checker to look for `.begin()`, `.end()`, `.size()` in the include directory.  It suggests using `rng::begin`, `rng::end`, `rng::distance`. You can also allow by adding `// dr-style ignore` to the line. For now, I only turned it on in mhp.
The only surprise was having to enable borrowed range for `remote_subrange`, but I think that is correct. You can see that below.
There are cases when `.begin()` is correct, but I think it is better to default to `rng::begin` in our code. Does this look ok? I intend to do the rest of the include directory, but not examples/tests.
> check for .begin, .end, .size in include directory

- test/gtest/shp/gemv.cpp
Disabling because of hard to reproduce failures. CI will still run it, but it will not cause a failure that blocks merging.
Run with:
```
./shp-tests --gtest_also_run_disabled_tests
```
> disable gemv because of failures

- include/dr/mhp/algorithms/algorithms.hpp
- include/dr/mhp/containers/distributed_vector.hpp
- test/gtest/include/common-tests.hpp
- test/gtest/include/common/distributed_vector.hpp
- test/gtest/mhp/mhp-tests.cpp
- test/gtest/shp/shp-tests.cpp
Support distributed vectors that are structure/class instead of built-in types. For MHP, there were problems where logging code assumed fmt knows how to print a value.
Tests are common, but SHP is disabled. It looks like sycl fill does not work.
Enabled `EXPECT_EQ` on distributed vectors. You need to define `operator==` and `operator<<`.  When they are free functions, they need to be defined in the same namespace as the class. It gets a little messy because the definitions are specific to the testing code.
> AOS support

- include/dr/shp/algorithms/for_each.hpp
- include/dr/shp/algorithms/inclusive_scan.hpp
- include/dr/shp/algorithms/reduce.hpp
- test/gtest/shp/algorithms.cpp
> Use `shp::devices()` inside algorithms, disable non-aligned

- .pre-commit-config.yaml
- include/dr/concepts/concepts.hpp
- include/dr/details/iterator_adaptor.hpp
- include/dr/details/ranges.hpp
- include/dr/mhp/containers/distributed_vector.hpp
- include/dr/shp/algorithms/copy.hpp
- include/dr/shp/algorithms/fill.hpp
- include/dr/shp/containers/index.hpp
- requirements.txt
- test/gtest/include/common-tests.hpp
- test/gtest/shp/containers.cpp
- test/gtest/shp/shp-tests.cpp
* Update pre-commit dependencies.
* Freeze python dependencies to avoid a sphinx plugin problem.
* @BenBrock: Disable `distributed_vector` tests for SHP because of random failures in fill constructor
> fix ci issues

- include/dr/mhp/containers/distributed_vector.hpp
- include/dr/shp/algorithms/fill.hpp
- test/gtest/include/common/fill.hpp
- test/gtest/shp/containers.cpp
- test/gtest/shp/shp-tests.cpp
workaround fill by not using queue fill, but parallel_for without kernel name
as described in CMPLRLLVM-46438
added unittests failing before and passing after the change
> using parallel_for instead of fill because of bug in fill

- include/dr/shp/algorithms/for_each.hpp
- include/dr/shp/algorithms/inclusive_scan.hpp
- include/dr/shp/algorithms/reduce.hpp
- test/gtest/shp/algorithms.cpp
Allow calling algorithms without execution policy in `shp`.
Calling an algorithm without an execution policy is equivalent to calling it with `shp::par_unseq`.
> Allow calling algorithms without execution policy

- include/dr/mhp/containers/distributed_vector.hpp
- test/gtest/mhp/mhp-tests.cpp
code was failing because dv_segments was treated by ranges library as a container and was wrapped by ref_view. ref_view takes address by object it references. But dv_segments happens to be a temporary object, so its address was becoming invalid. be deriving from view_base we instruct ranges library to treat dv_segments a view, not warp it by ref_view, but simply copy
> fixed dv_segments and enabled mhp::take tests

- include/dr/detail/halo.hpp
- include/dr/mhp.hpp
- test/cmake-application/CMakeLists.txt
- test/cmake-application/mhp-app.cpp
@tkarna: This should remove the dependence on format library.
I made an example, but not sure how to test in ci. This will download default branch from git. You can use the `URL` instead of `GIT_REPOSITORY` with `fetchcontent`, but you have to restructure the directory so the build directory is not in the tree.
> cmake example and remove dependence on format

- examples/mhp/CMakeLists.txt
- examples/mhp/stencil-slide.cpp
@BenBrock @mateuszpn 
This is the serial stencil using `rng::views::sliding`
Output:
```
[0, 100, 101, 102, 103, 104, 105, 106, 107, 0]
[0, 201, 303, 306, 309, 312, 315, 318, 213, 0]
[0, 504, 810, 918, 927, 936, 945, 846, 531, 0]
[0, 1314, 2232, 2655, 2781, 2808, 2727, 2322, 1377, 0]
[0, 3546, 6201, 7668, 8244, 8316, 7857, 6426, 3699, 0]
[0, 9747, 17415, 22113, 24228, 24417, 22599, 17982, 10125, 0]
```
> serial slide stencil

- .github/workflows/ci.yml
- doc/spec/source/algorithms/copy.rst
- doc/spec/source/concepts.rst
- include/dr/detail/communicator.hpp
- include/dr/detail/ranges.hpp
- include/dr/mhp/algorithms/algorithms.hpp
- include/dr/mhp/containers/distributed_vector.hpp
- include/dr/mhp/global.hpp
- include/dr/mhp/views/enumerate.hpp
- include/dr/mhp/views/segmented.hpp
- include/dr/mhp/views/views.hpp
- include/dr/mhp/views/zip.hpp
- include/dr/shp/algorithms/iota.hpp
- include/dr/shp/views/views.hpp
- include/dr/views/iota.hpp
- include/dr/views/transform.hpp
- scripts/dr-style.py
- test/gtest/common/zip.cpp
- test/gtest/common/zip_local.cpp
- test/gtest/include/common-tests.hpp
- test/gtest/mhp/CMakeLists.txt
- test/gtest/mhp/segmented.cpp
- test/gtest/mhp/xhp-tests.hpp
- test/gtest/shp/CMakeLists.txt
Only relies on `zip_view` and iterator having a base field.  It should be possible to implement the support for distributed with CPO's, but for now, local/segments/rank are MHP-specific methods. 
This implementation eliminates some of the issues with the earlier implementation. The views/iterators do not need to store std::vector. Instead, it implements the segments as a forward_range instead of a random_access_range. The iterator does not have pointers to the view.
> new mhp zip view

- examples/shp/CMakeLists.txt
- examples/shp/sort.cpp
- examples/shp/sort_benchmark.cpp
- include/dr/detail/onedpl_direct_iterator.hpp
- include/dr/shp/algorithms/algorithms.hpp
- include/dr/shp/algorithms/sort.hpp
- test/gtest/shp/algorithms.cpp
A sample sort-based implementation of `shp::sort`.  Basically, we sort locally, then pick a number of splitters, which will tell us which values go on which rank.  We then send values to the correct ranks, then perform a final sort.
We use the following algorithm:
- First, sort each local segment.  (Assume we have `p` segments.)
- On each process, identify `p-1` medians
- Pick `p-1` splitters by calculating the "median of the medians"
- Sort those `p*(p-1)` medians
- Pick `p-1` medians from this new sorted list
- Use `lower_bound` to calculate the offsets in each segments' sorted list that will be sent to each rank.
- Copy values to the destination ranks.
- Perform one last sort.
> Implement `shp::sort`

- test/gtest/common/zip.cpp
- test/gtest/mhp/xhp-tests.hpp
- test/gtest/shp/xhp-tests.hpp
@BenBrock: The last time I tried, this test would not compile with SHP
Leaving it in common zip tests, but enabling only for MHP
> enable zip IterSegments test for MHP

- include/dr/mhp/containers/distributed_vector.hpp
- include/dr/mhp/global.hpp
- include/dr/mhp/sycl_support.hpp
MHP `default_allocator` uses global context to choose sycl or system memory. This should make it possible to decide at runtime whether to target sycl or cpu. Avoids compile-time penalty for expanding multiple templates when only difference is type of memory used.
> mhp default_allocator 

- test/gtest/mhp/CMakeLists.txt
- test/gtest/mhp/mhp-tests.cpp
- test/gtest/mhp/xhp-tests.hpp
```
mhp-tests --sycl
```
Executes on sycl device. This avoids the need for building separate sycl and cpu tests and reduces CI time.
> mhp-tests runtime argument for using sycl

- test/gtest/mhp/xhp-tests.hpp
- test/gtest/shp/xhp-tests.hpp
CI takes 30 minutes, drop testing of float vectors and only test int to see if that will speed it up.
> drop testing of float vectors

- test/gtest/mhp/CMakeLists.txt
- test/gtest/mhp/slide_view-3.cpp
It is easier to write simple tests when one can assume there are only a fixed number of processes.
I'm creating a template for such a test. It is already going to be used in sliding-view and in dense-matrix.
> mpi 3 processes only test

- CMakeLists.txt
- benchmarks/gbench/common/distributed_vector.cpp
- benchmarks/gbench/mhp/CMakeLists.txt
- benchmarks/gbench/mhp/mhp-bench.cpp
- benchmarks/gbench/mhp/rooted.cpp
- benchmarks/gbench/mhp/xhp-bench.hpp
Added google benchmarks and implemented some micro benchmarks. DR is for distributed ranges and Local uses `std::/ranges::`
```
rscohn1@anpfclxlin02:mhp$ mpirun -n 1 ./mhp-bench --benchmark_time_unit=ms --reps 2
Configuration:
default vector size: 100000000
default repetitions: 2
run on CPU
2023-05-19T11:40:13-05:00
Running ./mhp-bench
Run on (96 X 3900 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x48)
L1 Instruction 32 KiB (x48)
L2 Unified 1024 KiB (x48)
L3 Unified 36608 KiB (x2)
Load Average: 0.04, 0.16, 0.10
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
***WARNING*** Library was built as DEBUG. Timings may be affected.
------------------------------------------------------------------
Benchmark …
```
> add gbench + some microbenchmarks

- benchmarks/gbench/common/distributed_vector.cpp
- benchmarks/gbench/common/dot_product.cpp
- benchmarks/gbench/mhp/CMakeLists.txt
- benchmarks/gbench/mhp/xhp-bench.hpp
- benchmarks/gbench/shp/CMakeLists.txt
- benchmarks/gbench/shp/xhp-bench.hpp
More microbenchmarks for dot product. Some measurements on a CPU-only system. MHP SYCL version has poor performance 😦. 
SHP outperforms DPL 🏆 
MHP
```
rscohn1@anpfclxlin02:mhp$ ../mhp/mhp-bench --benchmark_filter=DotProduct* --benchmark_time_unit=ms
Configuration:
default vector size: 100000000
default repetitions: 1
run on CPU
2023-05-21T07:51:16-05:00
Running ../mhp/mhp-bench
Run on (96 X 3900 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x48)
L1 Instruction 32 KiB (x48)
L2 Unified 1024 KiB (x48)
L3 Unified 36608 KiB (x2)
Load Average: 0.67, 1.87, 1.34
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
***WARNING*** Library was built as DEBUG. Timings may be affected. …
```
> more dot product microbenchmarks

- examples/mhp/CMakeLists.txt
Try to reduce CI fails with signal 9 by reducing memory size.
> reduce test mhp dot product size

- examples/mhp/CMakeLists.txt
Another attempt to prevent the signal 9 failures in github ci.
> mhp dot product, 1 rank for ci

- benchmarks/gbench/common/distributed_vector.cpp
- benchmarks/gbench/common/dot_product.cpp
- benchmarks/gbench/mhp/chunk.cpp
- benchmarks/gbench/mhp/mpi.cpp
- benchmarks/gbench/mhp/rooted.cpp
- benchmarks/gbench/mhp/stencil_1d.cpp
- benchmarks/gbench/mhp/stencil_2d.cpp
When benchmarking, use wall clock time instead of main thread time. SYCL CPU runtime is multi-threaded. Fixes the issue with SHP fill appearing to get 5 TB/s memory bandwidth.
> fix benchmarking issues

- include/dr/mhp/algorithms/copy.hpp
- include/dr/mhp/algorithms/for_each.hpp
- include/dr/mhp/algorithms/reduce.hpp
- include/dr/mhp/algorithms/transform.hpp
- include/dr/mhp/alignment.hpp
- include/dr/mhp/views/zip.hpp
- scripts/dr-style.py
- test/gtest/common/zip_local.cpp
- test/gtest/mhp/CMakeLists.txt
- test/gtest/mhp/alignment.cpp
Instead of trying to make the alignment understand what to do with an empty range, rely on the algorithm. This fixes an issue where a zip containing misaligned data was not reported as misaligned.
> rework alignment for empty ranges

- examples/shp/CMakeLists.txt
- examples/shp/black_scholes_benchmark.cpp
- include/dr/shp/util/sycl_utils.hpp
- include/dr/shp/zip_view.hpp
Implement Black-Scholes benchmark using `shp`.
This is essentially a fancy SAXPY operation.  We execute a `for_each` algorithm over multiple zipped arrays, operating on the corresponding elements.
```c++
template <typename T, dr::distributed_range RS, dr::distributed_range RX,
dr::distributed_range RT, dr::distributed_range RC,
dr::distributed_range RP>
void black_scholes_distributed(T r, T sig, RS &&s0, RX &&x, RT &&t, RC &&vcall,
RP &&vput) {
auto black_scholes = [=](auto &&e) {
auto &&[s0, x, t, vcall, vput] = e;
T d1 = (std::log(s0 / x) + (r + T(0.5) * sig * sig) * t) /
(sig * std::sqrt(t));
T d2 = (std::log(s0 / x) + (r - T(0.5) * sig * sig) * t) /
(sig * std::sqrt(t));
vcall = s0 * normalCDF(d1) - std::exp(-r * t) * x * normalCDF(d2);
vput = std::exp(-r * t) * x * normalCDF(-d2) - …
```
> Implement Black-Scholes benchmark

- .github/workflows/ci.yml
- benchmarks/gbench/mhp/CMakeLists.txt
- scripts/devcloud-run.sh
Improve CI turnaround time by switching all icpx testing to devcloud.
icpx testing on GitHub hosted runners takes ~30 minutes. Most of the time is building. GitHub hosted runners only have 1 core/2 threads and the icpx configuration builds the most files. We were already building the binary on devcloud so we could test on GPUs. Devcloud runners have many cores so builds only take a few minutes. The only thing it was not testing was running on a SYCL CPU device. Add an extra run on devcloud where only a CPU is available so we are getting full coverage and remove the icpx build on a GitHub hosted runner.
> use devcloud for icpx/cpu testing

- include/dr/mhp/algorithms/reduce.hpp
- scripts/dr-style.py
- test/gtest/mhp/slide_view-3.cpp
Sometimes it is not enough to write dr-style ignore comment because clang formatter puts `.size()` inside longer expression and comment is in next line. I think `comm.size()` can be allowed as a valid pattern of taking size of communicator.
> added exception in dr-style for .size() preceeded by comm variable

- benchmarks/gbench/mhp/mhp-bench.cpp
- include/dr/mhp/global.hpp
@jngkim Recommended adding this method for selecting GPU's for MHP. Previously, I was assuming that we would always be relying on external mechanisms like GPU pinning or resource managers to select GPU's, but @jngkim explained why that may not always work.
This algorithm should do the right thing for all cases of multi/single GPU, GPU pinning/ no pinning, partitionable devices/non partitionable.
@suyashbakshi: I did not test that it works on a multi-gpu system. Please fix it if you find problems.
> mhp gpu selection: round robin among ranks

- benchmarks/gbench/mhp/CMakeLists.txt
- include/dr/mhp/global.hpp
Fix a logic error in the earlier gpu pinning support. 
I assumed that it was being tested by mhp-bench tests, but we were not running mhp-bench with sycl enabled. Enabled mhp-bench  testing with --sycl. It found the problem. Thanks for @jngkim for tracking down the problem.
> fix gpu assignment for mhp

- benchmarks/gbench/mhp/stencil_2d.cpp
- include/dr/mhp/algorithms/stencil_for_each.hpp
- include/dr/mhp/views/mdspan_view.hpp
- test/gtest/mhp/CMakeLists.txt
- test/gtest/mhp/mdstar.cpp
Generalize stencil_for_each from 2 operands to support any number of operands. Verified that it has same stencil performance
> stencil_for_each: support arbitrary number of operands

- .cmake-format.py
- benchmarks/gbench/mhp/CMakeLists.txt
- test/fuzz/cpu/CMakeLists.txt
- test/gtest/mhp/CMakeLists.txt
- test/gtest/shp/CMakeLists.txt
I'd like to improve https://github.com/oneapi-src/distributed-ranges/pull/377 by making cmake function calls concise and introduce  config file.
I think
```
add_mpi_test(
mhp-bench-1 mhp-bench 1 --vector-size 30000 --rows 100 --columns 100
--check)
```
looks better than
```
add_mpi_test(
mhp-bench-1
mhp-bench
1
--vector-size
30000
--rows
100
--columns
100
--check)
```
@rscohn2 , does my change look OK to you?
> shorter cmake lists of arguments, cmake-format config added

- benchmarks/gbench/mhp/mdspan.cpp
- include/dr/detail/mdspan_utils.hpp
- test/gtest/mhp/mdstar.cpp
Primitives for manipulating local mdspan. To be used for 3d fft
* `mdspan_for_each `over index space of mdspan
* copies implemented with `mdspan_for_each`, works with mdspans that are slices (non-contiguous)
* mdspan to mdspan
* mdspan to contiguous container, pack data before send
* contiguous container to mdspan, unpack data after receive
* multi-dimensional transpose view that can be combined with the copies to do out-of-place transpose
> mdspan copy/pack/unpack/transpose

- benchmarks/gbench/mhp/CMakeLists.txt
- include/dr/mhp/algorithms/md_for_each.hpp
stencil_for_each and for_each over mdspans was limited to 2 dimensions. Now the CPU path supports any number of dimensions. SYCL support will be in a separate commit.
> Generalize mdspan for_each to handle any number of dimensions

- .github/workflows/ci.yml
- include/dr/detail/tuple_utils.hpp
- include/dr/mhp/algorithms/md_for_each.hpp
- test/gtest/mhp/mdstar.cpp
add tuple_foreach and tuple_transform to simplify md_foreach code. Gets rid of some tuple packing/unpacking and parameter pack folds.
> simplify md_foreach with tuple utilities

- examples/mhp/CMakeLists.txt
- examples/mhp/wave_equation.cpp
- test/gtest/mhp/CMakeLists.txt
- test/gtest/mhp/wave_kernel.cpp
> Wave equation example uses mdarray

- .github/workflows/daily.yml
- scripts/devcloud-build.sh
works in daily.yml
daily lasts 6 minutes
see: https://github.com/oneapi-src/distributed-ranges/actions/runs/5719036161/job/15496111873
> selective build fix

- .github/workflows/daily.yml
- .github/workflows/pr.yml
- CMakeLists.txt
- benchmarks/gbench/CMakeLists.txt
- src-python/drbench/drbench/drbench.py
- src-python/drbench/drbench/runner.py
On devcloud, we need to add --launcher=fork to mpirun commands to workaround a problem in their configuration. We were using command line switches to add the flag, but it was getting complicated and it was easy to make a mistake. Use an env variable instead. The CI yaml set the variables in 1 place. You should also add this to your `.bashrc` on devcloud if you want to run directly.
```
export MPIEXEC_EXTRA_FLAGS=--launcher=fork
```
@lslusarczyk @lslusarczyk: FYI
> replace mpifork flags with env variable

- benchmarks/gbench/common/inclusive_scan.cpp
- benchmarks/gbench/mhp/CMakeLists.txt
Filed ticket: ONEDPL-867
@lslusarczyk @BenBrock
> workaround dpl divot by passing std::plus to inclusive_scan benchmarks

- benchmarks/gbench/CMakeLists.txt
- src-python/drbench/drbench/plotter.py
black scholes runs out of memory with 4B, so use 2B
> bench: plot cores instead of sockets

- benchmarks/gbench/common/distributed_vector.cpp
- src-python/drbench/drbench/drbench.py
Skipping weak scaling for stream and black scholes because they do not do communication and do not have scaling issues.
iota with 32 bit initial value overflows. I try changing it to 64 bits but there are compile issues. To make progress, I eliminated iota use in benchmarks where there is a potential for overflow.
> weak scaling runs for reduce and inclusive scan

- benchmarks/gbench/common/dot_product.cpp
Random failures started here: https://github.com/oneapi-src/distributed-ranges/commit/de36e3a81cfef3f051211a4581adf7ac2280cc50#diff-ccdf102c9f46e5c5584559c5fa0f6fe49eac8fea40c9bbf29ac520a1bd2e301d
It is always dot product. See if this triggered the problem.
> change dot product to double to see if it caused failures

- benchmarks/gbench/common/dr_bench.hpp
- benchmarks/gbench/common/sort.cpp
- benchmarks/gbench/shp/CMakeLists.txt
measuring only sort, not preparing data for it
> fixed sort benchmarks, shp uses its own specific get_queue in benchmarks

- benchmarks/gbench/CMakeLists.txt
- benchmarks/gbench/common/dr_bench.hpp
- benchmarks/gbench/common/sort.cpp
- benchmarks/gbench/mhp/CMakeLists.txt
slow benchmarks in mhp were fixed by using global context and devices list just as in SHP
This will need to be further refactored, to remove redundant code and make shp/mhp use same code (now we have two implementations doing the same), but at least it works now and @mateuszpn may proceed with benchmarking sort.
> enabled sort benchmarks in mhp, fixed slow benchmarks in mhp

- benchmarks/gbench/mhp/wave_equation.cpp
- call `dr::mhp::halo(e).exchange_begin()` right after `e` has been updated
- call `dr::mhp::halo(e).exchange_finalize()` right before evaluating a stencil kernel that uses adjacent elements of `e`. Local elementwise assignments do not need up-to-date halos.
> Wave equation: overlap halo exchange and computation

- CMakeLists.txt
- test/gtest/mhp/CMakeLists.txt
Added ENABLE_ISHMEM disabled by default which enables targets related to work with ishmem
If it is enabled then _shmem_ target appears which compiles and installs level-zero, ofi, Sandia-OpenSHMEM IntelSHMEM into lib, include & build directories inside cmake build directory. This environment may be used to link against in e.g. mhp-shmem-test which is a sample target linking with new libs.
> compiling and linking with ishmem and its dependencies

- benchmarks/gbench/mhp/CMakeLists.txt
- benchmarks/gbench/mhp/wave_equation.cpp
- include/dr/mhp/algorithms/reduce.hpp
- test/gtest/common/reduce.cpp
- test/gtest/mhp/CMakeLists.txt
- test/gtest/mhp/halo.cpp
- test/gtest/mhp/mdstar.cpp
- test/gtest/mhp/mhp-tests.cpp
- test/gtest/mhp/segments.cpp
- test/gtest/mhp/xhp-tests.hpp
Disable tests that assume local memory is accessible from host
> Command line options to use device memory for wave equation and mhp-test

- src-python/drbench/drbench/drbench.py
disabled due to: https://github.com/oneapi-src/distributed-ranges/issues/593
> disbled shp Exclusive_Scan benchmarks

- src-python/drbench/drbench/drbench.py
- src-python/drbench/drbench/runner.py
disabled because they are very slow in mhp, see: https://github.com/oneapi-src/distributed-ranges/issues/588
> disabled mhp Exclusive_Scan benchmarks

- .github/workflows/pr.yml
I serialized CI jobs to reduce runner usage. I thought it would only add 2 minutes to the total time. I found that intel-unbuntu-latest always takes 4+ minutes to spin up, adding 10 minutes to total time. Do checks, g++, and icpx in parallel.
> do not serialize ci jobs

- benchmarks/gbench/CMakeLists.txt
- benchmarks/gbench/shp/shp-bench.cpp
- src-python/drbench/drbench/drbench.py
- src-python/drbench/drbench/runner.py
- src-python/drbench/pyproject.toml
- added possibility to runbenchmarks under icpx compiler from 2024.1 oneapi
- retrying failed benchmarking for limited time
- different-devices option supported on shp
- running benchmarks by mpiexec pointed by current I_MPI_ROOT, not by the path
- limited shp FFT3D_DR to 4 gpus as it fails with OUT_OF_RESOURCES if executed on more devices
- removed seaborn dependency from drbench package
> benchmarks framework refactoring

- include/dr/mhp/algorithms/inclusive_exclusive_scan_impl.hpp
- test/gtest/common/exclusive_scan.cpp
- test/gtest/common/inclusive_scan.cpp
- test/gtest/mhp/CMakeLists.txt
For small input vectors  (smaller than  2 * size(r)) sequential function is bug-safe.
> DRA-89 fixed (Bug in exclusive_scan for input ranges of small size)

- benchmarks/gbench/CMakeLists.txt
- src-python/drbench/drbench/drbench.py
- src-python/drbench/drbench/runner.py
As I noticed shp benchmarks fail with PI_OUT_OF_RESOURCES when running with more than 4 GPUs using 2024 oneAPI
> added target limiting shp benchmarks to 4 GPUs

- benchmarks/gbench/common/sort.cpp
- include/dr/detail/communicator.hpp
- include/dr/mhp/algorithms/sort.hpp
- include/dr/mhp/containers/distributed_vector.hpp
- test/gtest/common/sort.cpp
mhp::copy and mhp::sort updated to avoid 32-bit int limitations
> Support for input vectors bigger that 2GB

- .github/workflows/onedpl.yml
- .github/workflows/pr.yml
intel mandated changes:
* Use hash instead of branch/tag for github actions
* remove permissions for workflows
> resolve some github actions workflow security issues

- CMakeLists.txt
It is due to warning in cpp-format. And in order to ease project maintenance.
> treating warnings as errors no more
