.github/workflows/ci.yml
After this change ctest should print output what went wrong during test execution.
=> [CI] Append output from ctest failure

CMakeLists.txt
https://github.com/oneapi-src/distributed-ranges/issues/20
=> add support for the Debug configuration in CMakeLists

CMakeLists.txt, include/dr/algorithms/transpose.hpp, test/gtest/cpu/cpu-tests.hpp, test/gtest/cpu/mdspan.cpp
This is the same as in PR from @KFilipek: https://github.com/oneapi-src/distributed-ranges/pull/8, but I've removed optional as mdspan itself is an option (may be empty). See my last commit.
=> Transpose loc2dist

doc/spec/source/communication/communication.rst, doc/spec/source/communication/halo_bounds.rst, doc/spec/source/containers/distributed_vector.rst, examples/cpu/stencil-1d-cpu.cpp, include/dr/details/distributed_vector.hpp, include/dr/details/halo.hpp, test/gtest/cpu/span_halo.cpp, test/gtest/cpu/transform.cpp, test/gtest/sycl-mpi/distributed_vector.cpp, test/gtest/sycl-mpi/transform.cpp
removed partial support for multi-dimension halos.
=> simplify halo

include/dr/details/allocators.hpp, include/dr/details/segments_tools.hpp
I'm reviewing/learning current codebase.
A few simplifications from today.
=> simplifications

include/dr/views/transform.hpp
forgot to add this in earlier commit
=> capture value of fn in lambda

include/dr/shp/copy.hpp, include/dr/shp/distributed_vector.hpp, include/dr/shp/util.hpp, test/gtest/include/common-tests.hpp, test/gtest/shp/copy.cpp
Some of the new copy tests are failing when run on multiple GPUs.  I'm trying to investigate why.
=> Investigate failing copy test

CMakeLists.txt, examples/shp/test_range.cpp, include/CMakeLists.txt, include/dr/shp/util.hpp
@BenBrock: I am updating DPL to latest and adding a patch for a warning.
Removing the remaining use of sycl 2020 deprecations.
=> update DPL, cleanup deprecation warnings

include/dr/details/halo.hpp, include/dr/mhp.hpp, include/dr/mhp/containers/distributed_vector.hpp, test/fuzz/cpu/algorithms.cpp, test/gtest/include/common/dv-tests.hpp
=> mhp implement fill constructor

test/gtest/include/common-tests.hpp, test/gtest/include/common/view-tests.hpp
take is broken in MHP and disabled
=> common test subrange, take, drop

test/gtest/include/common-tests.hpp, test/gtest/include/common/algorithm-tests.hpp, test/gtest/include/common/view-tests.hpp, test/gtest/include/mhp-tests.hpp, test/gtest/mhp/mhp-tests.cpp, test/gtest/mhp/mhp-tests.hpp, test/gtest/shp/shp-tests.cpp, test/gtest/shp/shp-tests.hpp
Partially addresses #82 
Addresses #83
=> common test for zip/transform views

include/dr/shp/distributed_vector.hpp, include/dr/shp/vector.hpp, test/gtest/include/common-tests.hpp, test/gtest/mhp/mhp-tests.hpp, test/gtest/shp/CMakeLists.txt, test/gtest/shp/containers-3.cpp, test/gtest/shp/containers.cpp, test/gtest/shp/containers.hpp, test/gtest/shp/copy-3.cpp, test/gtest/shp/copy.cpp, test/gtest/shp/copy.hpp, test/gtest/shp/shp-tests.hpp
added unit tests for checking the size and the segments number of a distributed vector
=> add basic unit tests for a distributed vector

examples/mhp/CMakeLists.txt, examples/mhp/stencil-1d-array.cpp, include/dr/details/halo.hpp
@mateuszpn: This does not work because of an interaction of zip and subrange, but it does look like it will work for multiple processes.
=> 2d stencil using 1d arrays

examples/include/data-utils.hpp, examples/include/vector-add-serial.hpp, examples/mhp/vector-add-ref.cpp, examples/shp/inclusive_scan_example.cpp, examples/shp/test_range.cpp, examples/shp/vector_example.cpp, examples/shp/zip_example.cpp, include/dr/details/memory.hpp, include/dr/details/normal_distributed_iterator.hpp, include/dr/shp/algorithms/matrix/gemv.hpp, include/dr/shp/containers/dense_matrix.hpp, include/dr/shp/containers/matrix_partition.hpp, include/dr/shp/containers/sparse_matrix.hpp, include/dr/shp/distributed_span.hpp, include/dr/shp/distributed_vector.hpp, include/dr/shp/range.hpp, include/dr/shp/util.hpp, include/dr/shp/util/generate_random.hpp, include/dr/shp/vector.hpp, include/dr/shp/zip_view.hpp, scripts/dr-style.py, test/fuzz/cpu/cpu-fuzz.cpp, test/gtest/mhp/distributed_vector.cpp, test/gtest/shp/algorithms.cpp, test/gtest/shp/gemv.cpp
We were using `std::size_t` and `size_t`. Use `std::size_t` and enforce with dr-style.py
=> use std::size_t everywhere

.github/workflows/mirror.yml
Use github settings to set:
ENABLE_MIRROR 1
To enable mirroring the upstream repo
=> mirroring support

.github/workflows/ortce.yml
@BenBrock @lslusarczyk 
Feel free to adapt cluster/gpu testing. Tests only run on the mirror.
=> ortce testing

include/dr/mhp/alignment.hpp, include/dr/mhp/containers/distributed_vector.hpp, test/gtest/mhp/alignment.cpp
=> redo mhp distributed_vector iterator

examples/mhp/CMakeLists.txt, examples/mhp/dot_product_benchmark.cpp
=> add mhp dot product benchmark

examples/mhp/CMakeLists.txt, examples/mhp/dot_product_benchmark.cpp, include/dr/mhp/algorithms/reduce.hpp, test/gtest/mhp/CMakeLists.txt, test/gtest/mhp/reduce.cpp
dot product works for float
Still investigating problems with 1B data items. Results match DPL, but not sequential
=> rewrite mhp reduce, dot_product_benchmark

examples/mhp/dot_product_benchmark.cpp, include/dr/concepts/concepts.hpp, include/dr/detail/communicator.hpp, include/dr/detail/segments_tools.hpp, include/dr/mhp.hpp, include/dr/mhp/algorithms/algorithms.hpp, include/dr/mhp/algorithms/copy.hpp, include/dr/mhp/containers/distributed_vector.hpp, scripts/dr-style.py, test/gtest/common/distributed_vector.cpp, test/gtest/common/take.cpp, test/gtest/include/common-tests.hpp, test/gtest/mhp/CMakeLists.txt, test/gtest/mhp/copy.cpp
also change dot_product_benchmark to initialize with random numbers on root and copy to other processes
=> mhp: copy from/to local/remote contiguous ranges

examples/shp/black_scholes_benchmark.cpp
Apply a few common optimizations to Black-Scholes kernels.
=> Optimize Black-Scholes kernel

doc/user/placement.rst
@suyashbakshi: Please review this documentation. I used information from your spreadsheet. Instead of `-d` I used `ONEAPI_DEVICE_SELECTOR` so we would not have to add device selection logic to each program.
=> document placement

include/dr/detail/index.hpp, include/dr/mhp.hpp, include/dr/shp/algorithms/matrix/gemv.hpp, include/dr/shp/containers/dense_matrix.hpp, include/dr/shp/containers/matrix_entry.hpp, include/dr/shp/containers/matrix_partition.hpp, include/dr/shp/containers/sparse_matrix.hpp, include/dr/shp/util/coo_matrix.hpp, include/dr/shp/util/generate_random.hpp, include/dr/shp/util/matrix_io.hpp, include/dr/shp/views/csr_matrix_view.hpp, include/dr/shp/views/dense_column_view.hpp, include/dr/shp/views/dense_matrix_view.hpp, include/dr/shp/views/dense_row_view.hpp, include/dr/shp/views/standard_views.hpp
dr::shp::index moved to dr::index, to be used with dr::mhp as well
=> dr::shp::index moved to dr::index

CMakeLists.txt, benchmarks/gbench/mhp/CMakeLists.txt, benchmarks/gbench/shp/CMakeLists.txt, examples/mhp/CMakeLists.txt, examples/shp/CMakeLists.txt, include/CMakeLists.txt, test/gtest/mhp/CMakeLists.txt, test/gtest/shp/CMakeLists.txt
Global setting of -fsycl flag if SYCL is enabled.
=> -fscycl moved to top-level CMakeList.txt

examples/shp/CMakeLists.txt, test/gtest/shp/CMakeLists.txt
=> remove some unnecessary cuda compile options

include/CMakeLists.txt, test/gtest/common/inclusive_scan.cpp, test/gtest/mhp/CMakeLists.txt
moved oneDPL tag to commit on its main branch which contains my fix of oneDPL reduce bugfix merged
=> enabled back inclusive_scan tests with multiply

benchmarks/gbench/mhp/CMakeLists.txt, benchmarks/gbench/mhp/stencil_2d.cpp, include/dr/detail/mdspan_shim.hpp, include/dr/mhp.hpp, include/dr/mhp/algorithms/stencil_for_each.hpp, include/dr/mhp/containers/distributed_mdarray.hpp, include/dr/mhp/views/mdspan_view.hpp, include/dr/mhp/views/submdspan_view.hpp, test/gtest/mhp/mdstar.cpp
Gets same performance as the for_each with the builtin radius
=> add submdspan: mdspan version of subrange

.github/workflows/ci.yml, CMakeLists.txt, scripts/devcloud-build.sh, scripts/devcloud-run.sh
Devcloud requires --launcher=fork
=> support -launcher=fork for mpi

CMakeLists.txt
=> compiler opt flags from suyash

.github/workflows/ci.yml, CMakeLists.txt, benchmarks/gbench/CMakeLists.txt, benchmarks/gbench/mhp/CMakeLists.txt, benchmarks/gbench/mhp/mhp-bench.cpp, benchmarks/gbench/shp/CMakeLists.txt, benchmarks/gbench/shp/shp-bench.cpp, scripts/devcloud-benchmarks.sh, src-python/drbench/drbench/common.py, src-python/drbench/drbench/drbench.py, src-python/drbench/drbench/plotter.py, src-python/drbench/drbench/runner.py, src-python/drbench/pyproject.toml
- uses seaborn and pandas as @tkarna advised
- creates 6 column pandas.DataFrame out of all _essential_ informations in json files
- adding new plots in a few lines of code by using right selectors over DataFrame
- 2 examples of plots creating
=> benchmarks plotting

include/dr/mhp/views/mdspan_view.hpp, include/dr/mhp/views/segmented.hpp, test/gtest/mhp/mdstar.cpp
=> cleanup mdspan implementation

.github/workflows/daily.yml, .github/workflows/pr.yml, include/dr/mhp/algorithms/md_for_each.hpp
=> md foreach handles general decomposition

.github/workflows/daily.yml, benchmarks/gbench/CMakeLists.txt, scripts/devcloud-benchmarks.sh, scripts/devcloud-build.sh, src-python/drbench/drbench/drbench.py
- shorter daily.yml job (not compiling unnecesary binaries, not running already ran tests)
- added easy multiple filters support to dr-bench
=> shorter daily.yml job and multiple filters support to dr-bench

scripts/devcloud-build.sh
@lslusarczyk
Disabling selective build so I can make progress.
=> workaround daily scripting bug

src-python/drbench/drbench/runner.py
Was using GPU when CPU was requested
=> Fix bench targeting for SHP

examples/mhp/dot_product_benchmark.cpp, include/dr/mhp/algorithms/reduce.hpp, include/dr/mhp/global.hpp
Just a draft with some minor modifications I made when running mhp's `dot_product_benchmark`.
=> Some minor updates for mhp's `dot_product_benchmark` example

.github/workflows/daily.yml, benchmarks/gbench/shp/CMakeLists.txt, src-python/drbench/drbench/plotter.py
=> add black scholes plot

benchmarks/gbench/common/distributed_vector.cpp
Check results. Without the check, the compiler was optimizing away the computation.
=> reduce memory requirements for reduce

.pre-commit-config.yaml, benchmarks/gbench/CMakeLists.txt, doc/spec/source/conf.py, pyproject.toml, scripts/dr-style.py, src-python/drbench/drbench/drbench.py, src-python/drbench/drbench/plotter.py, src-python/drbench/drbench/runner.py
* cleanup some dr-bench code, add more debugging support
* remove pyproject.toml: black was ignoring it when pre-commit ran as a git commit hook, so add black args in .pre-commit instead
=> dr-bench cleanup and debugging support

benchmarks/gbench/common/sort.cpp, benchmarks/gbench/shp/CMakeLists.txt, src-python/drbench/drbench/drbench.py
reduce running time, add std version, move to common.
Disable DPL version in benchmark runs because it is extremely slow
=> some changes to sort

benchmarks/gbench/common/black_scholes.cpp, benchmarks/gbench/mhp/CMakeLists.txt, src-python/drbench/drbench/drbench.py, src-python/drbench/drbench/plotter.py
I tried to extract the black_scholes lambda function but I had some problems with function definitions (class _Function) that's why this is still a draft PR (copy paste of the lambda function), any suggestions are welcome
=> added a DPL version of the black_scholes benchmark

include/dr/detail/mdspan_utils.hpp, include/dr/detail/sycl_utils.hpp, include/dr/detail/utils.hpp, include/dr/mhp/algorithms/for_each.hpp, include/dr/mhp/algorithms/inclusive_scan.hpp, include/dr/mhp/algorithms/md_for_each.hpp, include/dr/shp/algorithms/exclusive_scan.hpp, include/dr/shp/algorithms/for_each.hpp, include/dr/shp/algorithms/inclusive_scan.hpp, test/gtest/common/sycl_utils.cpp, test/gtest/mhp/CMakeLists.txt
=> extend parallel_for workarounds to 2d

benchmarks/gbench/mhp/CMakeLists.txt, benchmarks/gbench/mhp/wave_equation.cpp, examples/mhp/CMakeLists.txt, examples/mhp/wave_equation.cpp, src-python/drbench/drbench/drbench.py
Init and error checking were slow because they did element-wise reads on remote data. Change it to be parallel where ranks work on local data.
=> wave_equation parallel init/checking

benchmarks/gbench/mhp/stencil_2d.cpp
Makes performance comparable to Stencil2D_DR
=> use ndrange for Stencil2D_Reference

benchmarks/gbench/mhp/wave_equation.cpp
- adds read/write/flop statistics to wave equation
- add those to the benchmark stats too
- fail correctly if L2 error is NaN
=> Add wave equation statistics

examples/shp/fft3d.cpp
* Implement fft3d in examples/shp
=> Created a fft3d example

benchmarks/gbench/mhp/wave_equation.cpp, include/dr/mhp/containers/distributed_mdarray.hpp
- add `distributed_mdarray.extent` method
- use it in wave equation benchmark
=> Add distributed_mdarray extent method

src-python/drbench/drbench/drbench.py, src-python/drbench/drbench/runner.py
using logging module
also measuring and printing time of individual command to ease narrowing down most time consuming commands
=> logging time in dr-bench messages

benchmarks/gbench/mhp/fft3d.cpp
* Add init 
* Fix plan creation 
* Fix call order in compute_backward
=> Fixes for FFT3D-mhp

CMakeLists.txt, benchmarks/gbench/mhp/mhp-bench.cpp, include/dr/detail/communicator.hpp, include/dr/mhp/containers/distributed_vector.hpp, include/dr/mhp/containers/segment.hpp, include/dr/mhp/global.hpp, test/gtest/common/distributed_vector.cpp, test/gtest/include/common-tests.hpp, test/gtest/mhp/CMakeLists.txt, test/gtest/mhp/mhp-tests.cpp, test/gtest/mhp/shmem_basic.cpp
depending on DRISHMEM compilation flag distributed vector is 
- either compiling with rdma window or with ishmem allocated memory
- either using MPI or ishmem_getmem/ishmem_putmem for put&get
Most of current distributed-vector tests pass. Non passing ones were commented in ishmem test and will be enabled one by one by future work.
=> ishmem, working distributed_vector put and get and most of its tests

test/gtest/common/counted.cpp
fixed the countedOfFirstSegementHasOneSegmentAndSameRank test
=> fix counted test (when more ranks than assumed)

src-python/drbench/drbench/plotter.py
It will be needed in order to see historical benchmark results.
=> creating index.rst file by plotter

.github/workflows/pr.yml, benchmarks/gbench/mhp/fft3d.cpp, benchmarks/gbench/shp/CMakeLists.txt, include/dr/detail/mdspan_utils.hpp, include/dr/mhp/halo.hpp, test/gtest/shp/CMakeLists.txt
I couldn't find a case when shp-tests or shp-bench fail
=> Enable shp-tests

.github/workflows/pr.yml
currently it is empty, added it in order to be able to mark it as required as I still have admin rights this week :)
=> added package task

.github/workflows/pr.yml, CMakeLists.txt, benchmarks/gbench/sp/CMakeLists.txt, include/CMakeLists.txt, test/gtest/common/sort.cpp, test/gtest/mp/CMakeLists.txt
Temporary change (for ~ 1 week) because of movement of PVC-based CI to new network.
=> running CI on CPU and public runners
